---
title: Hello World! - Kadalu Technologies
author: aravindavk
description: "Hello World!"
---

== Kadalu

Kadalu is a Kannada word which means Ocean.

== Open Source

Kadalu Open Source project was started in 2019 with the focus on developing a natively integrated easy to use storage solution for Kubernetes. Later the idea was extended for non-Kubernetes use cases as well and started a new Glusterd alternative "Moana".

A few popular Kadalu Open source projects are:

=== Kadalu Kubernetes Storage
Natively integrated with Kubernetes APIs and uses Gluster core file system layer to provide Storage for the apps running on Kubernetes.

=== Kadalu Storage
With the modern Storage manager, easily manage the Storage resources using CLI, ReST APIs or using the web interface.

=== Binnacle
A test framework focused on Tester's delight.

=== Gluster Metrics Exporter
Prometheus and JSON exporter for Gluster metrics.

=== Gdash
Simple web dashboard for GlusterFS.

== Company

On _Apr 15, 2022_, **Kadalu Technologies** is incorporated with the focus on providing enterprise support for the Kadalu Storage, GlusterFS feature development and consultancy services.
